<html>
<head>
 <title>Российский экономический университет имени Г.В Плеханова</title>
</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">

<link href="index.css" type="text/css" rel="STYLESHEET">

<table border=1 width=100% height=20%>

<tr>

<td width=100% height=20% align=center> Лабораторные работы по курсу "Веб-программирование" <br> Студента группы ПИс-141: Барменко Максима Евгеньевича <br> Проверил: к.т.н. доц. Назимов А.С. </td>

</table>
<table border=1 width=100% >
<td width=30% align=left valign=top>
<a href="orderform.php">  Первая лабораторная работа </a>
<br><br>
<a href="orderform_2.php">  Вторая лабораторная работа </a>
<br><br>
<a href="orderform_3.php">  Третья лабораторная работа </a>
<br><br>
<a href="orderform_3_1.php">  Третья лабораторная работа (ООП) </a>
<br><br>
<a href="orderform_4.php">  Четвертая лабораторная работа </a>
<br><br>
<a href="index_5.php">  Пятая лабораторная работа </a>
<br><br>
<a href="index_6.php">  Шестая лабораторная работа </a>
</td>

<td width=70%  align=center> 
